name: Build and create artifacts for dot net core 7 CLI app

on: [tag]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Build and create artifacts for Windows
      run: dotnet publish -c Release -r win-x64 --self-contained true
      shell: pwsh
      working-directory: ./src/Commitex.Console

    - name: Archive artifacts for Windows
      uses: actions/upload-artifact@v2
      with:
        name: Commitex-Windows-x64
        path: ./src/Commitex.Console/bin/Release/net7.0/win-x64/publish

    - name: Build and create artifacts for Mac
      run: dotnet publish -c Release -r osx-x64 --self-contained true
      shell: pwsh
      working-directory: ./src/Commitex.Console

    - name: Archive artifacts for Mac
      uses: actions/upload-artifact@v2
      with:
        name: Commitex-MacOS-x64
        path: ./src/Commitex.Console/bin/Release/net7.0/osx-x64/publish
